<?php

	namespace Traineratwot\PhpCli\types;

	use Traineratwot\PhpCli\Type;

	class TypeFloat extends Type
	{
		public static $shotName = 'float';

		public function validate($value)
		{
			return is_numeric($value) ? TRUE : 'Invalid float "'.$value.'"';
		}

		public function get()
		{
			return (float)parent::get(); // TODO: Change the autogenerated stub
		}
	}